name: CI/CD to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install && npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - run: echo "Listing all files in dist directory:" && ls -la .
      - name: Upload build to Digital Ocean
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DIGITAL_OCEAN_SSH_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_SSH_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_SECRET_KEY }}
          port: ${{ secrets.DIGITAL_OCEAN_SSH_PORT }}
          source: "dist/*,package.json,compose.yaml"
          target: "/home/paulo/apps/outlai/"
      - name: Finish deploy to Digital Ocean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DIGITAL_OCEAN_SSH_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_SSH_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_SECRET_KEY }}
          port: ${{ secrets.DIGITAL_OCEAN_SSH_PORT }}
          script: |
            npm install &&
            pm2 restart outlai-app &&
            echo "Finished deploy to Digital Ocean from Github Actions. Date $(date)" >> /home/paulo/ssh-deploy.log
